version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    build: .
    restart: always
    ports:
      - "80:4000"
    volumes:
      - ./content-management-system:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - backend